### ISSUE TITLE
Running redcar 0.8.1 on Windows 7 x64

### ISSUE THREAD

**Issue by ddm** [danlucraft/redcar#5]
I am trying to get redcar to run on a windows 7 x64 box but I am getting the following error:

```
Redcar 0.8.1 ( java )
Error loading plugin: <Plugin swt 1.0 depends:[dep(core >0)] 0 files>
  cannot link Java class org.eclipse.swt.widgets.Display, probable missing dependency: Cannot load 32-bit SWT libraries on 64-bit JVM
  c:/devtools/jruby-1.5.3/lib/ruby/site_ruby/shared/builtin/javasupport/java.rb:51:in `method_missing'
  C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/plugins/swt/lib/swt.rb:129
  C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/plugins/swt/lib/swt.rb:31:in `require'
  c:/devtools/jruby-1.5.3/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
  C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/lib/plugin_manager/lib/plugin_manager/plugin_definition.rb:41:in `load'
  C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/lib/plugin_manager/lib/plugin_manager/plugin_definition.rb:58:in `log_requires'
  C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/lib/plugin_manager/lib/plugin_manager/plugin_definition.rb:40:in `load'
  C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/lib/plugin_manager/lib/plugin_manager.rb:128:in `load_plugin'
  C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/lib/plugin_manager/lib/plugin_manager.rb:109:in `load'
  C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/lib/redcar.rb:111:in `load_prerequisites'
  C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/lib/redcar.rb:142:in `load_threaded'
  C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/bin/redcar:28
  C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/bin/redcar:19:in `load'
  c:\devtools\jruby-1.5.3\bin\redcar:19
C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/plugins/swt/lib/swt.rb:50:in `show': uninitialized constant Swt::Graphics (NameError)
        from C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/plugins/swt/lib/swt.rb:97:in `create_splash_screen'
        from C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/lib/redcar.rb:168:in `show_splash'
        from C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/bin/redcar:29
        from C:/devtools/jruby-1.5.3/lib/ruby/gems/1.8/gems/redcar-0.8.1/bin/redcar:19:in `load'
        from c:\devtools\jruby-1.5.3\bin\redcar:19
```

The error seems to indicate a problem with SWT being the 32-bit version. Since eclipse based application run fine on my machine I guess there is something I am missing here.

Steps I used to install redcar:
- download and install jruby (used the 64-bit executable)
- run `jruby -S gem install redcar` to install the redcar gem
- run `redcar install`

I also tried to install from source but with the same result.

**Comment by danlucraft** [comment]
Hey, I replied on StackOverflow. Also, I'm very sorry but I don't know why issues are turned on on this repo. We use redcar.lighthouseapp.com for bugs, and I've opened this one here, which you can watch if you want to get updated:
https://redcar.lighthouseapp.com/projects/25090-redcar/tickets/375-redcar-does-support-64bit-windows
